### ISSUE TITLE
Double-Opt-In and Customer-activation

### ISSUE THREAD

**Issue by Saga1987** [enrico69/magento2-customer-activation#10]
Hi @enrico69 
first of all thank you for this module!
I have the following problem:
Our client whish to have double-opt-in AND admin customer-activation, but it seems, that these won't work together. It is ok, that the customer can log-in after e-mail-validation, but the message, that the account is waiting for admin-validation, won't show up. Any ideas? 
Using 2.1.3 CE but the update to 2.2 CE is planned soon.

**Comment by enrico69** [comment]
Hi @Saga1987 

If I understand your customer needs:
- that the customer confirms (via the link send to its email address)
- that the admin user activate the account.

If I understand your issues:
- The user receives the confirmation email and can click on the link
- But, then, it can connect to the site even if the user admin hasn't activated the account?

**Comment by Saga1987** [comment]
Hi @enrico69 ,
thanks for your fast reply!

I try to explain the should-be workflow:

1. Customer create account, get validation-e-mail (double-opt-in)
2. Customer confirm his account, is allowed to log in (it works until here)
3. After that, the message should be send to the admin, that customer is waiting for approval. (Until now, admin get this message **before** confirming)
4. Until admin approve the account, the message "Your account is waiting for validation... " shall be shown on frontend to the logged-in, not validated customer. (this message didn't show up at all, maybe because the customer already logged in using the confirmation-mail-link).

Hope you understand my needs (and sry for my bad english)

**Comment by enrico69** [comment]
OK for the point # 3. A small "if" has to be added here: 
https://github.com/enrico69/magento2-customer-activation/blob/45acf33a38e8bb0d2981b6f4a1df038c0e7ba52e/Observer/UserActivation.php#L94
to check if the email validation by the customer is enabled for the given store or not.
The same if has to be added in a new plugin when the customer confirm its address.
This is some new development to do.

Regarding the point # 4 I don't understand. If the admin didn't validate the user account, your customer can connect to the site?

**Comment by Saga1987** [comment]
Thanks for the hint, I will check this out.

To point 4: Yes, the customer can connect to the site (I think otherwise the confirmation wouldn't work?), but if he place an order, the order-status will be "pending" until validation by admin.

**Comment by enrico69** [comment]
> Thanks for the hint, I will check this out.

I meant you have to override my module, not to modify its code :)

> To point 4: Yes, the customer can connect to the site (I think otherwise the confirmation wouldn't work?), but if he place an order, the order-status will be "pending" until validation by admin.

I meant, what does-it currently? Not what you want to do at the end...
What's the result now?

**Comment by Saga1987** [comment]
> I meant, what does-it currently? Not what you want to do at the end...
What's the result now?

Ah sorry, I didn't get this right.
Currently the customer can connect to the site after confirmation, no message is shown, that the account is waiting for validation.  It's like your module wasn't installed at all.
But if I disable double-opt-in, your module works just fine.

**Comment by enrico69** [comment]
OK then I confirm your last point: this bug comes from the fact that the Magento core code is not clean regarding this functionnality, and doesn't use the same part when autlogging from the confirmation email.

So this bug correction and the enhancement for the admin notification email will be released in 1.4.

**Comment by enrico69** [comment]
Bug fixed in release 1.4
Funcationnality added in 1.4
