### ISSUE TITLE
Customer Grid

### ISSUE THREAD

**Issue by Jmarles** [enrico69/magento2-customer-activation#11]
Hi @enrico69 ,

Is it possible to have account active attribute in customer grid so admin can quickly see what accounts are active?

**Comment by enrico69** [comment]
Yes it is.
I will try to do it this week.

**Comment by enrico69** [comment]
Done.
Will be released in 1.4, very soon.

**Comment by Jmarles** [comment]
Thanks @enrico69 , you're a legend!

**Comment by enrico69** [comment]
Done in release 1.4

**Comment by Jmarles** [comment]
Thanks very much for the new release.  However, since upgrading the module I can no longer see the filter or columns options above the customer grid.  Would this be a caching issue or a conflict with the upgrade?

**Comment by enrico69** [comment]
Did-you:
-run a magento setup:upgrade
-run a magento indexer:reindex
-run a magento cache:clean

**Comment by enrico69** [comment]
I confirm there is a small issue: the filter columns options appears only if you scroll down. I am working on it.

**Comment by enrico69** [comment]
Fixed in 1.4.1

**Comment by Jmarles** [comment]
Thanks @enrico69 
The filter options are working fine now with latest release, however, the activation column is not updating after a customer has been activated.  The column is still says no even though the account is active and email has been sent.

**Comment by enrico69** [comment]
Probably because I rely on Magento to extract the data. Magento use a flat table regenerated by CRON jobs. So the data should be updated sooner or later... Let me know!

**Comment by enrico69** [comment]
Any news?

**Comment by Jmarles** [comment]
Hi @enrico69 ,

My crons must not have been running properly.  I made a few changes and when i logged into the system this morning the customer status was showng as active
