### ISSUE TITLE
Magento 2.2.1: Customer Grid Empty

### ISSUE THREAD

**Issue by LSERRE** [enrico69/magento2-customer-activation#12]
I tried your module and faced lot of issues on Magento 2.2.1

First customer grid in backofice display 0 customer when I got lot of customers in database.
Secondly when I reindex I got: Customer Grid index is locked by another reindex process. Skipping.

**Comment by enrico69** [comment]
Hi @LSERRE 

A "lot of issues" is not enough to help you.

- Which version of MG2 are you using ? EE or CE?
- Have you other modules related to the customers installed and activated on your Magento instance?

I have not tried the last version of the module on 2.2.1, so this is what I suggest:
- 1:  As blocked indexers is a common issue in MG2, please read this link to try to reindex: [here](https://magento.stackexchange.com/questions/126067/magento-2-how-to-unlock-reindex-process)
- 2: If you are still experiencing issues: downgrade the module to the 1.3.2 version

Keep us in touch. If you still have the problem we will try on our side.

**Comment by LSERRE** [comment]
Hi, 

Thanks for your answer. 

I installed 1.3.2 version and Customer grid is working now. Thanks

**Comment by enrico69** [comment]
So at the beginning you were using 1.4.1 ?

**Comment by LSERRE** [comment]
Yes, the master branch.

I still got the issue when I try to reindex:

PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Customer\Model\Indexer\Source::addAttributeToSelect() in /home/104764-79551.cloudwaysapps.com/xgyghcmfxk/public_html/vendor/magento/framework/Indexer/Handler/AttributeHandler.php:38

**Comment by enrico69** [comment]
Ok.
So if I sum-up:
- 1.3.2 is fine
- 1.4.1 is buggy.

**Comment by LSERRE** [comment]
I reinstalled 1.4.1 and still got empty customer grid. 
I will check your code. If I found the problem I will do a pull request.

**Comment by enrico69** [comment]
OK thanks!

**Comment by LSERRE** [comment]
The grid is still empty and now I get:
"Customer Grid index is locked by another reindex process. Skipping."
When trying to reindex even when i disable the module.

So I guess the problem comes from InstallData.php or UpgradeData.php

You should really check this issue because your module can brake merchant client database.

**Comment by enrico69** [comment]
We are going to check this issue.

However your comment is not very suited: this module can't "break" anything as it:
- doesn't create any table
- doesn't modify any core table
- doesn't modify any core data not related to it.

A I told you in my first message, a blocked indexer (just look a the link...) is not a rare issue in Magento 2.

By the way, I disabled the >= 1.4.0 release from packagist.

**Comment by mjrmurray** [comment]
Having same problem with v1.4.1 and v1.3.2 in M2 2.2.1 CE

On install: 
Customer Grid index is locked by another reindex process. Skipping.

While using:
Empty customer grid.  On attempt to reindex:

[@]# php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:02
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Customer\Model\Indexer\Source::addAttributeToSelect() in /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Handler/AttributeHandler.php:38
Stack trace:
#0 /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Action/Base.php(310): Magento\Framework\Indexer\Handler\AttributeHandler->prepareSql(Object(Magento\Customer\Model\Indexer\Source), 'e', Array)
#1 /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Action/Entity.php(26): Magento\Framework\Indexer\Action\Base->createResultCollection()
#2 /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Action/Base.php(179): Magento\Framework\Indexer\Action\Entity->prepareDataSource(Array)
#3 /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Action/Base.php(189): Magento\Framework\Indexer\Action\Base->execute()
#4 /var/www/html/PFB/inventory/vendor/magento/module-indexer/Model/Indexer.php(412): Magento\Framework\Indexer\Action\Base->executeFull()
#5 /var/www/html/PFB/invento in /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Handler/AttributeHandler.php on line 38

Completely removed source code, cleared cache, recompiled, and customer indexing is still broken.  Do you have an idea how i can fix this issue?  I'm still getting the indexing exception above and customer grid is not loading.  I have completely removed the module.

**Comment by enrico69** [comment]
Hi mjrmurray.
We are correcting this Bug.
However, before the release of the fix, please use the 1.3.2 version.

**Comment by mjrmurray** [comment]
Thanks, unfortunately I installed v. 1.4.1 first.  That action must have added something to the DB because even after installing v.1.3.2 after uninstall, it still will not index the customer grid.  I'll simply wait for the update, or re-deploy a backup.  Thanks.

**Comment by enrico69** [comment]
To deblock the indexer, please read the link above in this topic.

**Comment by mjrmurray** [comment]
You misunderstand.  Indexer is not blocked.  It's throwing an exception when attempting to index.

PHP Fatal error: Uncaught Error: Call to undefined method Magento\Customer\Model\Indexer\Source::addAttributeToSelect() in /var/www/html/PFB/inventory/vendor/magento/framework/Indexer/Handler/AttributeHandler.php:38

unblocking the indexer and re-indexing fails every time.

**Comment by enrico69** [comment]
Ok then just make a save of your db and then edit the is-active attribute to set it no usable and not visible on the customer grid.

**Comment by mjrmurray** [comment]
Worked.  You da man.  Thanks.

**Comment by enrico69** [comment]
Is a Magento issue:  https://github.com/magento/magento2/issues/10838
Try to adapt the module.

**Comment by enrico69** [comment]
As you can see, it is not related to our module, but to Magento itself.
On a fresh install of Magento 2.2.4-dev, I still have the issue.

So we are waiting for a correction on their side to see what to do. Until then, 1.3.2 is the last stable version of our module.

**Comment by LSERRE** [comment]
I did a mistake and installed your module on production. Now my customer grid is empty. I tried to set is-active attribute to not usable and not visible in grid in db, my customer grid is still empty in backoffice. Then I tried to delete both attributes added in your module in eav_attributes, customer_eav_attributes and my grid still empty. Could you please help me? Thanks.

**Comment by enrico69** [comment]
This is what I would do:
- disable the module
- delete the entry in setup_modules
- delete the module files
- rename the is_active attribute to anything else
- reindex

**Comment by LSERRE** [comment]
It doesn't work neither.

**Comment by enrico69** [comment]
Do you have any filter set in the customer grid?
Did the reindexation worked without error?
Did you clean the cache?
Do you have others third party module linked to the customer?

Thats very weird. First time I see that.
This also could be something not related with the module. I saw this kind of issue on Magento 1. A SQL error because a request was too long to execute for example...
A quick look on Google give some hints.

**Comment by rafaelcalero** [comment]
Apparently version 1.4.1 breaks the Magento database. It's what is happening to @LSERRE 

**Try the following to cause the error:**
1. Install latest version of the module and everything else.
At this moment your customer index is "destroyed"

Then you can:

> disable the module
delete the entry in setup_modules
delete the module files
rename the is_active attribute to anything else
reindex 

**But still the customer index will be broken**. In the installation process you are probably making some change in the database. And this doesn't allow to uninstall the module completely.

**Comment by enrico69** [comment]
@rafaelcalero 
I disagree. I did not have any issue to uninstall the module and get the indexer to work. And if you read the complete topic, one user did it too.

On top of that, you can check the source code, I do not do "some change" in the database neither it break it and I used magento built-in features. Look by yourself and do not hesitate to make your contribution, but before PLEASE read this whole topic ;)

**Comment by enrico69** [comment]
For those still following this issue: the Magento Team didn't fix the problem yet.
However you could easily and quickly create a temporary fix, as explained [here](https://github.com/magento/magento2/issues/10838).

Reminder: create your own module to make this fix, never edit the core code directly.

**Comment by enrico69** [comment]
It seems that some are still facing the issue because of Magento...
So we implemented the fix directly in the 1.4.2 to be released this week.

**Comment by rafaelcalero** [comment]
@enrico69 I'm looking forward to trying it

**Comment by enrico69** [comment]
Fix is done. The 1.4.2 version will also include another fix (still related to the version 2.2.x de Magento which has a lot of side effects). The release will be available this week-end or next monday.

**Comment by enrico69** [comment]
Fixed in 1.4.2.

**Comment by enrico69** [comment]
Note: according to https://github.com/magento/magento2/issues/10838 it has been fixed in the 2.2.4 release of Magento. So it is very likely that we will remove the fix from our module and hence it will no longer compatible with version inferior to Magento 2.2.4.
