### ISSUE TITLE
Pull custom EAV Attributes in Admin Activation email?

### ISSUE THREAD

**Issue by clasteroid** [enrico69/magento2-customer-activation#16]
Sorry, not as much an issue as a troubleshooting request. I am trying to add a custom customer attributes in the activation email that is sent to the admin once a user registers.
 I am on version 1.4.2  from the readme.md file.

I am adding the following line into Observer/UserActivation.php
$newCustomer = $this->customerRepository->get($customer->getCustomAttribute('company_name')->getValue());

And adding the following line into Model/AdminNotifications.php
 ->setTemplateVars(['companyname' =>  $customer->getCustomAttribute('company_name')->getValue()]);

And then I am adding {{var customer.custom('company_name')}} into the view/frontend/email/new-customer-notification.html

Attribute id from the EAV_Attribute table is 425

I totally understand if you can't help with this since it's not necessarily an issue. Module works great otherwise. Using with the redirect module you've built as well. Thanks for any help!

**Comment by enrico69** [comment]
Hi

No problem, I will help you if I can.

I notice a little thing: 

> And adding the following line into Model/AdminNotifications.php
> ->setTemplateVars(['companyname' => $customer->getCustomAttribute('company_name')->getValue()]);
> 
> And then I am adding {{var customer.custom('company_name')}} into the view/frontend/email/new-customer-notification.html

In the template var your variable is named _**companyname**_
while in the template itself you call it by the name **_company_name_**.

And what is the purpose of this code:

> I am adding the following line into Observer/UserActivation.php
> $newCustomer = $this->customerRepository->get($customer->getCustomAttribute('company_name')->getValue());

Regards

**Comment by clasteroid** [comment]
Thanks for the reply! I removed the code from the observer at Observer/UserActivation.php per your instructions.

The registration forum is still not sending correctly unless I only have one variable in my AdminNotifications file at Model/AdminNotifications.php .

So with the following it will send the company_name variable correctly:
           /* ->setTemplateVars(['email' => $customer->getEmail()]), */
             ->setTemplateVars(['company_name' => $customer->getCustomAttribute('company_name')->getValue()]);

With the Email line un commented it will fail.

This is the variables I am using to receive 'company_name'
{{var company_name|raw}}

Any ideas? Is my separator , or ; messing it up between the ->setTemplateVars lines?
Thanks for the help!

**Comment by enrico69** [comment]
Could you show us the code you used to create the customer attribute "company_name"?

**Comment by clasteroid** [comment]
The attribute 'company_name' was created through the a registration module which I am not sure if I can post the code for. I can send you the installation data file privately though if you want?

Here is my entire Model/AdminNotification.php file:
`<?php
namespace Enrico69\Magento2CustomerActivation\Model;

use Magento\Framework\Mail\Template\TransportBuilder;
use Magento\Framework\App\Area;
use Magento\Store\Model\Store;
use Magento\Store\Model\StoreManagerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

class AdminNotification
{
    protected $transportBuilder;

    /**
     * @var \Magento\Store\Model\StoreManagerInterface
     */
    protected $storeManagerInterface;

    /**
     * @var \Magento\Framework\App\Config\ScopeConfigInterface
     */
    protected $scopeConfigInterface;

    /**
     * ActivationEmail constructor.
     * @param \Magento\Framework\Mail\Template\TransportBuilder $transportBuilder
     * @param \Magento\Store\Model\StoreManagerInterface $storeManagerInterface
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfigInterface
     */
    public function __construct(
        TransportBuilder $transportBuilder,
        StoreManagerInterface $storeManagerInterface,
        ScopeConfigInterface $scopeConfigInterface
    ) {
        $this->transportBuilder = $transportBuilder;
        $this->storeManagerInterface = $storeManagerInterface;
        $this->scopeConfigInterface = $scopeConfigInterface;
    }

    /**
     * Send an email to the site owner to notice it that
     * a new customer has registered
     *
     * @param \Magento\Customer\Api\Data\CustomerInterface $customer
     * @throws \Magento\Framework\Exception\MailException
     */
    public function send($customer)
    {
        $siteOwnerEmail = $this->scopeConfigInterface->getValue(
            'trans_email/ident_sales/email',
            ScopeInterface::SCOPE_STORE,
            $customer->getStoreId()
        );

        $this->transportBuilder->setTemplateIdentifier('enrico69_activation_email_notification')
            ->setTemplateOptions(
                [
                    'area' => Area::AREA_FRONTEND,
                    'store' => $customer->getStoreId(),
                ]
            )
            ->setTemplateVars(['email' => $customer->getEmail()]);
            /* ->setTemplateVars(['company_name' => $customer->getCustomAttribute('company_name')->getValue()]); */
             
        $this->transportBuilder->addTo($siteOwnerEmail);
        $this->transportBuilder->setFrom(
            [
                'name'=> $this->storeManagerInterface->getStore($customer->getStoreId())->getName(),
                'email' => $siteOwnerEmail
            ]
        );
        
        $this->transportBuilder->getTransport()->sendMessage();
    }
}`

**Comment by enrico69** [comment]
OK What is the error do you get.
Did you put a logger to see if `$customer->getCustomAttribute('company_name')->getValue()` return the correct value?

**Comment by clasteroid** [comment]
I will learn how to put a logger in tomorrow and see if i can get you a result. 
`$customer->getCustomAttribute('company_name')->getValue()` did return the correct value when I commented out 
         `->setTemplateVars(['email' => $customer->getEmail()]);`

Thanks for the help! I really appreciate it!

**Comment by clasteroid** [comment]
This ended up working for me to pass both variables at once to the email.
 ->setTemplateVars(
             [
             		'email' => $customer->getEmail(),
             		'company_name' => $customer->getCustomAttribute('company_name')->getValue()
             		]
             );

And I used `{{var company_name|raw}}` to receive the variable in the view/frontend/email/new-customer-notification.html

**Comment by enrico69** [comment]
Perfect. I close then.

**Comment by clasteroid** [comment]
Awesome, thanks so much for the help!
