### ISSUE TITLE
New Customers don't show up in Customer Index

### ISSUE THREAD

**Issue by DigicreateJens** [enrico69/magento2-customer-activation#4]
After installing the module and enabling it, new Customers don't show up in the Customer Index anymore. All Customers that registered before enabling the module are shown correctly.

If I modify the `edit url` for an _old_ Customer, I can edit the Customer without any issues. But even when I activate the Customer, it still doesn't show up in the Index.

Thanks for the module, it really helps me out a lot!

**Comment by enrico69** [comment]
Hi @DigicreateJens 

I am going to look for this soon and I will keep you updated.

**Comment by DigicreateJens** [comment]
Hey @enrico69 

Cool, thanks! If you can point me in the right direction I could potentially look into it myself and send a PR?

**Comment by enrico69** [comment]
@DigicreateJens 

I don't know where to look exactly. Firstly I am going to try to reproduce the issue.
You are free to search on your side and potentially make a PR!

**Comment by enrico69** [comment]
@DigicreateJens 

So if I understand properly, you cannot see new customers in the customers list in the Magento admin.

I didn't manage to reproduce the issue.

I use Magento 2.1.7 EE.

This is what I did:
- started on a "clean" database : the module has never been installed on it ;
- I have two websites on this Magento instance: I created a user account on both, with succes, they are visible in the admin ;
- I installed the activation module, enabled it, but did not enabled the parameter to request account validation ;
- I created a user account on the two sites: with success and they are visible on the admin ;
- On one of the website, I set the parameter to request account validation to true ;
- I created a user account on both, with success, they are visible in the admin, and on one of them the user account is not active ;

Question: did you try to clean the Magento cache? Have you something special with your indexers?

**Comment by DigicreateJens** [comment]
@enrico69 

Thanks for the quick feedback! After your last comment I did a indexer:reindex and now it seems to be showing all my customers correctly... Problem was probably on my end, sorry about that!

Thanks again for the feedback and if I can be of any assistance to this module, let me know 👍

**Comment by enrico69** [comment]
@DigicreateJens 
In fact yes you could start with a minor contribution :)

When I look at the user manual (_README.md_) of the module, I only wrote to make a _cache:clean_. But I always do a _indexer:reindex_ when I install this module somewhere. I think you could add it to the README.md
