### ISSUE TITLE
Exception #0 (InvalidArgumentException): Plugin class Enrico69\Magento2CustomerActivation\Plugin\Create doesn't exist

### ISSUE THREAD

**Issue by superdea** [enrico69/magento2-customer-activation#5]
Hi,

I know that the plugin has not been tested with 2.1.8, but maybe this is an issue that has not to do with magento version? if so, please let me know if there is a simple solution to the error.

The error occurs when a visitor tries to register. 
1. All data has been added to the registration form 
2. The "Create" button is clicked

Result:

1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class Enrico69\Magento2CustomerActivation\Plugin\Create doesn't exist

Exception #0 (InvalidArgumentException): Plugin class Enrico69\Magento2CustomerActivation\Plugin\Create doesn't exist
#0 /home/magentos/public_html/vendor/magento/framework/Interception/PluginList/PluginList.php(250): Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins('Magento\\Custome...')
#1 /home/magentos/public_html/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(35): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\\Custome...', 'dispatch')
#2 /home/magentos/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#3 /home/magentos/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#4 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#5 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#6 /home/magentos/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#7 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#8 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#9 /home/magentos/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#10 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#11 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#12 /home/magentos/public_html/app/code/Litespeed/Litemage/Model/App/FrontController/LitemagePlugin.php(71): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#13 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Litespeed\Litemage\Model\App\FrontController\LitemagePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#14 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#15 /home/magentos/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#16 /home/magentos/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#17 /home/magentos/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#18 /home/magentos/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#19 /home/magentos/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#20 /home/magentos/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /home/magentos/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Basicphp\Customurl\Magento\Framework\App\Request\Http2))
#22 /home/magentos/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /home/magentos/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main}

Looking forward to any response regarding the issue

/superdea

**Comment by enrico69** [comment]
Hi @superdea 

That's weird. According to your stacktrace, the plugin class that is called after the _CreatePost_ controller seems to not exist! But this class is well present in the module.

Questions:

- How did you install the module? Via composer? Manually ( put the module into _app/code_)?
- Do you use the last version of the module?

**Comment by superdea** [comment]
Hi,

Thanks for your answer. I downloaded and installed manually the latest available module.

/Sabina

**Comment by enrico69** [comment]
OK we are going to check.

**Comment by enrico69** [comment]
I tried a manual installation like yours (but on a 2.1.7) and I don't have the issue. I will try on a 2.1.8 later (however one user told us it used it on a 2.1.8 CE without problems).

In the meantime:

- could you give use the aborescence of you app/code folder? Where you installed the module.

- Have you other third-party modules installed which could have any effect on the customer creation process?

- Also: could you try to make a compilation of the DI (magento setup:di:compile) ?

**Comment by enrico69** [comment]
Any news?

**Comment by enrico69** [comment]
I am closing this ticket because we are still waiting for any news.
