### ISSUE TITLE
Welcome Email

### ISSUE THREAD

**Issue by Jmarles** [enrico69/magento2-customer-activation#6]
Changing the Welcome email template within admin area doesn't seem to work.

**Comment by enrico69** [comment]
Hi.
Could you give us the complete procedure to reproduce this error?

**Comment by enrico69** [comment]
We need more information:

- How did you install the module?
- What special configuration have you done?
- What is the error message?
- You mention a new email template: could you give us a copy?

**Comment by Jmarles** [comment]
![screenshot](https://user-images.githubusercontent.com/3810474/32170070-0992cf28-bd6b-11e7-951d-8f1669f0733f.jpg)


I created a new email template within Magento (2) admin area.  I then changed the settings in customer configuration for the system to use the new email template under that store view - see screenshot above.
Were these the correct steps to take?

**Comment by enrico69** [comment]
- Can you give me the content of your new template?
- Does-it work with the default template?

**Comment by Jmarles** [comment]
The default template that comes with your code works grand, but it is in plain text.  I wanted to include the shop email header and footer found in other email templates - see screenshot below...

![email-template](https://user-images.githubusercontent.com/3810474/32171663-d73b05bc-bd70-11e7-9cb9-fcf49949c1e5.jpg)

**Comment by enrico69** [comment]
OK.
What is the exact error message that you get?

**Comment by Jmarles** [comment]
Hi Enrico69,
I don't receive any error.  Magento simply ignores my settings within admin area for the new welcome email template and sends out the default email, referenced in your code - view/frontend/email/activation.html.

**Comment by enrico69** [comment]
OK!
Which version of Magento 2 are you using?

**Comment by Jmarles** [comment]
Magento ver. 2.1.7

**Comment by enrico69** [comment]
EE or CE ?

**Comment by enrico69** [comment]
Confirmed on 2.1.7 EE.

**Comment by Jmarles** [comment]
It's on Magento 2.1.7 Community Edition.  I am also using multiple stores, but I have ensured that the new email template has been set on the store I wanted it sent from - see previous screenshot - https://user-images.githubusercontent.com/3810474/32170070-0992cf28-bd6b-11e7-951d-8f1669f0733f.jpg

**Comment by enrico69** [comment]
Hi @Jmarles 

In fact you were confusing the Magento email that welcome the user and the email sent by this module when the user account is activated. So the behavior was normal.

However, because it makes sense, I added the feature to the 1.3.0. You can now select the activation confirmation email template in the store configuration.

**Comment by Jmarles** [comment]
STEP 1:  After installing your extension via FTP, I logged into admin configured the settings to only be enabled on our "Trade" store and then tested if it worked by registering as a customer on that store view.  All worked as expected! Customer received initial email (default magento welcome email), admin received email alerting them to a new registration (this came from your extension view/frontend/email/new-customer-notification.html) and I was able to activate the test customer through the admin area.  After which, the test customer (me) received a second email notifying me that my account was active.  This email also came from your extension - view/frontend/email/activation.html

STEP 2:  I wanted to provide our customers with a more detailed email once their account was active, so I edited your email template - view/frontend/email/activation.html - to change the text. After testing, this also worked, but the activation email was in plain text without any branding, etc.

STEP 3: In an attempt to jazz up the look/feel of the activation email I created a new email template in the admin area of Magento 2.  I went to Marketing/Email Templates and created a new email template, including the default header and footer found in other Magento 2 emails.

STEP 4: Staying within Magento 2 admin area, I went to Stores/Configuration/Customers/Customer Configuration and changed the store view to be "Trade Store View".  Within the Customer configuration options there is a field called "Welcome Email" with a dropdown to select different email templates.  I selected the new email template that I created in STEP 3 and after saving the settings, I tested it again to see if I would now receive my newly created Welcome email after my account was activated. 

However, after registering and activating my account the welcome email ignored my settings within Customer configuration and just sent the default email template from your extension - view/frontend/email/activation.html 

Sorry for the long winded (and badly explained) response.  The long and short of the issue is that the "Welcome Email " option within Stores/Configuration/Customers/Customer Configuration doesn't seem to be working!   No matter what I select here, your extension always reverts back to the default activation email.

**Comment by enrico69** [comment]
OK this is what I understood. But our activation email is not related to the welcome email sent by Magento!

So update the extension and you will get a new option in the store configuration to select your own template:

![image](https://user-images.githubusercontent.com/6852249/32338832-37b02620-bff6-11e7-980e-2fbaf50dc3fd.png)

**Comment by Jmarles** [comment]
Thanks @enrico69 , that worked great.  You're a star!!
