### ISSUE TITLE
Account active

### ISSUE THREAD

**Issue by jordielitzer** [enrico69/magento2-customer-activation#7]
Hello,

The plugin works, but how can i enable the new customer?
I search on the customer account (backend), but i cant found it..:(

Best regards,
Jordi 
![schermafbeelding 2017-10-31 om 15 47 16](https://user-images.githubusercontent.com/12067285/32230163-d34b607c-be52-11e7-936c-72416704619b.png)

**Comment by enrico69** [comment]
That is very strange! You should see it just above "Activation email sent"!
Did you make a _indexer:reindex_ and a _cache:clean_ (both in the console) ?

**Comment by jordielitzer** [comment]
Yes i have done that, see picture. 

Best regard,
Jordi

![schermafbeelding 2017-10-31 om 16 19 30](https://user-images.githubusercontent.com/12067285/32232024-5f9de578-be57-11e7-9c3f-789539ac25e0.png)

**Comment by enrico69** [comment]
Very strange. The usual procedure is to run the following commands:
- magento setup:upgrade
- magento indexer:reindex
- magento cache:clean

Which version of Magento are you using?

**Comment by jordielitzer** [comment]
I have try it a couple time's. 

I use version 2.2.0.

**Comment by enrico69** [comment]
EE or CE ?

**Comment by jordielitzer** [comment]
I'am sorry, i use CE

**Comment by jordielitzer** [comment]
Do you need login information, so you can check it?

Best regards,
Jordi

**Comment by enrico69** [comment]
I confirm: I have the same issue with the last 2.2 CE from the develop branch. It seems they made some modifications since the creation of the module.
I am going to adapt  that quickly!

**Comment by enrico69** [comment]
OK I found a solution. I will update the module this week.

**Comment by jordielitzer** [comment]
Hi,

Great! Thanks for the quick help :)


Best regards,
Jordi

**Comment by enrico69** [comment]
OK now it should be OK!
