### ISSUE TITLE
It doesn't disconnect new users

### ISSUE THREAD

**Issue by gianiaco** [enrico69/magento2-customer-activation#8]
Hello enrico69,
i tried to use this incredible extension on the new 2.2.1 CE version but it doesn't disconnect the new users.
Can you check?
Thanks

**Comment by enrico69** [comment]
Hi.
OK I am going to check.
Just a couple of simple questions: How did you installed it and did you follow instructions on the Readme?

**Comment by gianiaco** [comment]
I installed it on 2.2.0 by composer and then i had to do a setup:upgrade of course. Btw i can assure that before update to 2.2.1 it worked.

**Comment by enrico69** [comment]
Ah! Do you have the last version of the module (1.3)?

**Comment by gianiaco** [comment]
Yes, can't you reproduce on your desk?

**Comment by gianiaco** [comment]
Some news? 
I would to know if it's a version problem or only mine..
Thanks for patience

**Comment by enrico69** [comment]
I installed it directly on a 2.2.1 CE and no problems.
I am going to try your procedure: install it on a 2.2.0 CE and upgrade to 2.2.1.

**Comment by gianiaco** [comment]
Ok thanks for your help.
I attached a screen where you can see that account is not active actually but however i can login anyway.
Maybe is a good idea unistall and reinstall module? How can i do it?
![pr](https://user-images.githubusercontent.com/33554340/32729737-11b3f130-c885-11e7-9dbc-3075e0946ebd.png)

**Comment by enrico69** [comment]
Question: is the module still active?

**Comment by gianiaco** [comment]
Yes, after bin/magento module:status
List of enabled modules:
Enrico69_Magento2CustomerActivation
Magento_Store
Magento_Directory
Magento_Eav
...

**Comment by enrico69** [comment]
And when you are going in the store settings, the admin activation is still set to "yes"?

**Comment by gianiaco** [comment]
Sure
![sure](https://user-images.githubusercontent.com/33554340/32730098-49d3c6e8-c886-11e7-90c6-87f7b89cf144.png)

**Comment by enrico69** [comment]
Could you try (if not already done) to set it to "No", reindex and clean cache. Then set it to "Yes", reindex and clean cache again?

**Comment by gianiaco** [comment]
I just tried, no way...
Do you think i should try to unistall and reinstall?

**Comment by enrico69** [comment]
The concern is that there is currently no automatic uninstall script (it should come soon). If you do it, you will have some "dead" attributes in you database + the new ones.

**Comment by enrico69** [comment]
I am currently cloning a 2.2.0.

**Comment by gianiaco** [comment]
Are there only 2 attributes? One for activation and one for email? I can delete them manually

**Comment by enrico69** [comment]
Yes only those two.
And in the core_config table there should also be an attribute for the configuration (you should look here first).

**Comment by enrico69** [comment]
Those elements need to be checked first:

![image](https://user-images.githubusercontent.com/6852249/32730850-9ea451b8-c888-11e7-9f54-9c38fce47c6a.png)

**Comment by gianiaco** [comment]
Nothing... i tried and re-tried... 
No errors anywhere, i can't understand :|

**Comment by enrico69** [comment]
OK. So we are going to debug manually.

Using a debugger, put some breakpoints (or, if you don't have a debugger, put an old _exit("I am here")_ ) in the following line :
https://github.com/enrico69/magento2-customer-activation/blob/master/Plugin/Create.php#L76
and
https://github.com/enrico69/magento2-customer-activation/blob/master/Plugin/Create.php#L79

And tell me what happens when you create a new user account.

**Comment by gianiaco** [comment]
Ok now i think what could be!
Reading your code i remembered that i have this plugin installed too
https://github.com/php-cuong/magento2-redirect-customer
In particulary the code here
https://github.com/php-cuong/magento2-redirect-customer/blob/master/Observer/CustomerLogin.php#L70

Maybe it has higher "priority" so when i log in with a new account it redirect me at custom page avoiding your redirect here!
https://github.com/enrico69/magento2-customer-activation/blob/master/Plugin/Create.php#L85

How can i set "priority"? Some nice advice?

**Comment by enrico69** [comment]
This module is a horror show :dagger:  haha!
Let me explain:
- first of all it uses an observer. In Magento 2, you have to use plugins as often as possible (in this case, you can) ;

- then, even if you use an observer, you should NEVER put code that could short-circuit the others. Putting a redirection in an observer is a complete nonsense

- Using an exit(), in 2017, is probably the worst thing. In this case, it prevents the execution of the code after, including some Magento logic. I understand why he did it, but it is clearly inapropriate.

- exit() is not a function, it is a language construct. The parenthesis are useless if no parameter is given

- using double equal to compare code is a security flaw

- and, the most annonying: as far I know in Magento 2 you cannot prioritize observers, while you can do it with plugins. On top of that, as the observer of this developer is triggered before my _afterExecute_ plugin, my code is never reached.

Sorry but I have currently no solution for this one...

**Comment by enrico69** [comment]
Actually I have a solution : you can create a plugin in your project. This plugin would be similar to mine afterExecute one. It would look if the path is a redirect respond to the customer account (the default Magento behavior). If it is the case, you can redirect where you want. If not, do nothing.

I am going to ask the developer of the other module :p

**Comment by gianiaco** [comment]
Ok you are so clear and very kind. Thanks for explanations!
The last question is:
instead of create a new plugin can i simply add here
https://github.com/enrico69/magento2-customer-activation/blob/master/Plugin/Create.php#L88
an else with a banal redirect? If yes what are the right row of code? 
These ones should be ok?

$resultRedirect = $this->resultRedirectFactory->create();
$resultRedirect->setPath('**_mypath_**');
$result = $resultRedirect;

**Comment by enrico69** [comment]
It would work but would be a bad practice: 
- never edit third-party code : only override it
- it would be reset by any update of my module (if you do it)

I am going to create my own module to do what your want. It is very simple and easy. I will let you know soon!

**Comment by enrico69** [comment]
HI @gianiaco 

Could you please test this : 
https://github.com/enrico69/magento2-redirect-on-login
It should do the job you are waiting for :)

**Comment by gianiaco** [comment]
Thanks @enrico69 !!
I'll try it in next days
