### ISSUE TITLE
Custom Fields on Email Template

### ISSUE THREAD

**Issue by Jmarles** [enrico69/magento2-customer-activation#9]
Hi @enrico69 

Can you tell me how to reference a custom field in an email template?  
I want to be able to amend the A "new customer registered" email sent to Admin to include all the customer's details including custom fields.

I tried the following:
Trading Name: {{var data.trading_name}}
AND
{{trans "Trading Name: %tradingName" tradingName=$data.trading_name}}

But neither worked.  Any suggestions?

**Comment by enrico69** [comment]
Hi @Jmarles !

If you look at [these lines](https://github.com/enrico69/magento2-customer-activation/blob/master/Model/AdminNotification.php#L69) :


`->setTemplateVars(['email' => $customer->getEmail()]);`

you can see that the very minimum of informations are given in the email template.

I think it could be an evolution that, instead of passing only the customer email, to pass the whole customer object, so you could access whatever you want from the template. What do you think about it?

**Comment by Jmarles** [comment]
Thanks for the advice.
Let me give it a go and I'll let you know how I get on.

**Comment by Jmarles** [comment]
Hi @enrico69 
I tried the code below, but it didn't work.  Any advice?
`    public function send($customer)
    {
        $siteOwnerEmail = $this->scopeConfigInterface->getValue(
            'trans_email/ident_sales/email',
            ScopeInterface::SCOPE_STORE
        );
        $customer_attributes = $this->objectManager->get('Magento\Customer\Model\Customer')->getAttributes();

        $attributesArrays = array();

           foreach($customer_attributes as $cal=>$val){
               $attributesArrays[] = array(
                   'label' => $cal,
                   'value' => $cal
               );
           }


        $this->transportBuilder->setTemplateIdentifier('enrico69_activation_email_notification')
            ->setTemplateOptions(
                [
                    'area' => Area::AREA_FRONTEND,
                    'store' => Store::DEFAULT_STORE_ID,
                ]
            )
            ->setTemplateVars(array('data' => $attributesArrays));

        $this->transportBuilder->addTo($siteOwnerEmail);
        $this->transportBuilder->setFrom(
            [
                'name'=> $this->storeManagerInterface->getStore($customer->getStoreId())->getName(),
                'email' => $siteOwnerEmail
            ]
        );
        
        $this->transportBuilder->getTransport()->sendMessage();
    }`

**Comment by enrico69** [comment]
Which result do you get?

**Comment by Jmarles** [comment]
I got an error saying account could not be created and none of the customer emails were sent.

**Comment by enrico69** [comment]
OK. Checkck your logs to get the exact error message. The whole stacktrace would be a must :)

**Comment by Jmarles** [comment]
[13-Nov-2017 15:30:13 UTC] PHP Parse error:  syntax error, unexpected '$this' (T_VARIABLE) in 
 /public_html/app/code/Enrico69/Magento2CustomerActivation/Model/AdminNotification.php on line 78

LINE 78 refers to the following:
`$this->transportBuilder->setTemplateIdentifier('enrico69_activation_email_notification')`

**Comment by enrico69** [comment]
I am sorry I cannot help you on this point. You have programmation error.
For example the first line of you message show a syntax error (PHP).
Then I see you use `$this->objectManager` while $this->objectManager is not declared anywhere...

**Comment by enrico69** [comment]
However I am going to make some tests on my side to help you.

**Comment by Jmarles** [comment]
Thanks @enrico69 
I'll try declaring ObjectManager and test it again.

**Comment by Jmarles** [comment]
Declaring ObjectManager allowed for the customer to be registered.  However the email was sent out with the following error:
Error filtering template: Warning: htmlspecialchars() expects parameter 1 to be string, array given in /home/derrysdev/public_html/vendor/magento/module-email/Model/Template/Filter.php on line 69

**Comment by enrico69** [comment]
OK. The message is clear.
Go to the file /_home/derrysdev/public_html/vendor/magento/module-email/Model/Template/Filter.php_ at the given line to log or dump the content of the given parameter to understand where it comes from.

**Comment by Jmarles** [comment]
In my email template I was trying to get the value for Trading name using the following:
<p>Trading Name: {{var data.trading_name}}</p>
When I dumped the content this is what was returned:

`Array ( [0] => Array ( [label] => entity_id [value] => entity_id ) [1] => Array ( [label] => increment_id [value] => increment_id ) [2] => Array ( [label] => website_id [value] => website_id ) [3] => Array ( [label] => store_id [value] => store_id ) [4] => Array ( [label] => created_in [value] => created_in ) [5] => Array ( [label] => group_id [value] => group_id ) [6] => Array ( [label] => account_is_active [value] => account_is_active ) [7] => Array ( [label] => account_activation_email_sent [value] => account_activation_email_sent ) [8] => Array ( [label] => prefix [value] => prefix ) [9] => Array ( [label] => firstname [value] => firstname ) [10] => Array ( [label] => middlename [value] => middlename ) [11] => Array ( [label] => lastname [value] => lastname ) [12] => Array ( [label] => suffix [value] => suffix ) [13] => Array ( [label] => email [value] => email ) [14] => Array ( [label] => password_hash [value] => password_hash ) [15] => Array ( [label] => default_billing [value] => default_billing ) [16] => Array ( [label] => default_shipping [value] => default_shipping ) [17] => Array ( [label] => confirmation [value] => confirmation ) [18] => Array ( [label] => created_at [value] => created_at ) [19] => Array ( [label] => updated_at [value] => updated_at ) [20] => Array ( [label] => dob [value] => dob ) [21] => Array ( [label] => failures_num [value] => failures_num ) [22] => Array ( [label] => taxvat [value] => taxvat ) [23] => Array ( [label] => first_failure [value] => first_failure ) [24] => Array ( [label] => gender [value] => gender ) [25] => Array ( [label] => rp_token [value] => rp_token ) [26] => Array ( [label] => lock_expires [value] => lock_expires ) [27] => Array ( [label] => rp_token_created_at [value] => rp_token_created_at ) [28] => Array ( [label] => disable_auto_group_change [value] => disable_auto_group_change ) [29] => Array ( [label] => trading_name [value] => trading_name ) [30] => Array ( [label] => website [value] => website ) [31] => Array ( [label] => newsletter_product_interests [value] => newsletter_product_interests ) [32] => Array ( [label] => mobile_number [value] => mobile_number ) [33] => Array ( [label] => job_title [value] => job_title ) [34] => Array ( [label] => retailer_type [value] => retailer_type ) [35] => Array ( [label] => your_location [value] => your_location ) ) `

**Comment by Jmarles** [comment]
I also tried calling a default customer field to see if there was any issues with my custom fields.  The following code did not return anything:
Hi {{var firstname | raw}}

**Comment by Jmarles** [comment]
Hi @enrico69,
How did you get on with your tests?  Based on the content dump, I'm not sure my code is retrieving any customer information.  Have you any ideas where I'm going wrong?
Thanks
